server:
  port: 9001
spring:
  application:
    name: chess-auth-center
eureka:
  client:
    service-url:
      defaultZone: http://120.78.94.125:7001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
chess:
  jwt:
    secret: chess@Login(Auth}*^31)&yun6%f3q2 # 登录校验的密钥
    pubKeyPath: E:\id_rsa.pub # 公钥地址
    priKeyPath: E:\id_rsa.pri # 私钥地址
    expire: 600 # 过期时间,单位分钟
    cookieName: CHESS_TOKEN
    cookieMaxAge: 36000