server:
  port: 8003
spring:
  application:
    name: chess-rankhis-service
  datasource:
      url: jdbc:mysql://120.78.94.125:3306/chese
      username: chese
      password: 1234
  redis:
    host:
eureka:
  client:
    service-url:
      defaultZone: http://120.78.94.125:7001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
mybatis:
  type-aliases-package: com.chess.rankhis.enty
logging:
  level:
    root: info
history:
  showcount: 5

