server:
  port: 8086
spring:
  application:
    name: chess-email
  rabbitmq:
    virtual-host: /
    username: guest 
    password: guest
    host: 120.78.94.125
    port: 5672
#  redis:
#    host: localhost
  mail: 
    host: smtp.qq.com
    username: 429667810@qq.com
    password: lwjyxywkdwhhbghg
    properties: 
      mail:
        smtp:
          auth: true  # 需要验证登录名和密码
        starttls:
          enable: true  # 需要TLS认证 保证发送邮件安全验证
          required: true
chess: 
  register: 
    url: http://localhost:8001/activeAcount